### ISSUE TITLE
Android API Contract

### ISSUE THREAD

**Issue by sean-perkins** [sean-perkins/nativescript-opentok#10]
Do your best to match the existing call signature for iOS, in Android. We need to expose the event callbacks (listeners) from the Android SDK to the demo app, in order to allow users to attach custom logic to event firings. 

For example, in iOS the demo app has this call signature:

```
this._session.sessionEvents.on('sessionDidConnect', (result) => {
    console.log('sessionConnected event');
    this._session.publish();
    this._session.publisherEvents.on('streamCreated', () => {
        console.log('streamCreated event on publisher object');
    });
});
```

Parent task: #12

**Comment by triniwiz** [comment]
Done
