### ISSUE TITLE
Fix Video Issue on Android

### ISSUE THREAD

**Issue by sean-perkins** [sean-perkins/nativescript-opentok#11]
Currently in Android, the device will force quit the camera as soon as it attempts to publish the feed. Identify the issue causing the camera to quit and fix it, so that the publisher camera is visible on the device and/or emulator. 

Parent issue: #12

**Comment by triniwiz** [comment]
https://github.com/sean-perkins/nativescript-opentok/commit/949ccedf5c743e25d04e03a623b3dd12e276e2bd
