### ISSUE TITLE
Subscribe to Stream - Android

### ISSUE THREAD

**Issue by sean-perkins** [sean-perkins/nativescript-opentok#13]
Refer to this diagram:

![image](https://cloud.githubusercontent.com/assets/13732623/17702982/101d958a-639e-11e6-91f4-fe9ffd692ea3.png)

The device needs to follow the appropriate flow to allow two users to publisher and subscribe to each other's feeds. Their camera feeds should display on each other's devices, as well as their own camera feed should be visible on the screen. Think of the same concept as iOS FaceTime.

![Image](http://i.dailymail.co.uk/i/pix/2015/04/27/20/281228A100000578-0-image-a-1_1430161213878.jpg)

Parent issue: #12

**Comment by triniwiz** [comment]
Done
