### ISSUE TITLE
Better Implementation of Appending Video Stream

### ISSUE THREAD

**Issue by sean-perkins** [sean-perkins/nativescript-opentok#14]
Currently the video streams are added to the activity/frame using an absolute layout. I believe the video streams are actually added to a new activity that is placed over the existing foreground activity. 

Investigate a better way to control where the video streams are published to. Ideally you would be able to specify a container ID to append the stream to. 

If this is not possible, we need to find a better way to allow users to change the video stream's location and size, after it has been appended to the view. 

Parent Issue: #12

**Comment by triniwiz** [comment]
https://github.com/sean-perkins/nativescript-opentok/commit/949ccedf5c743e25d04e03a623b3dd12e276e2bd & https://github.com/sean-perkins/nativescript-opentok/commit/dd8b071c292207ce3469cfe39ec8c6cd9ea9b592 done with custom tags `<TNSOTPublisher>` , `<TNSOTSubscriber>`
