### ISSUE TITLE
Allow Configuration to BaseVideoRenderer

### ISSUE THREAD

**Issue by sean-perkins** [sean-perkins/nativescript-opentok#15]
There are 3 different ways that a video is displayed on the screen:
- Fill
- Fit 
- Scale

Allow the user to configure this, prior to appending the stream to the screen.

API Reference: https://www.tokbox.com/developer/sdks/android/reference/com/opentok/android/BaseVideoRenderer.html

Parent issue: #12

**Comment by triniwiz** [comment]
This can be done like the following 

`<OT:TNSOTPublisher render_style="fill" id="publisher" verticalAlignment="top" horizontalAlignment="right" margin="10" width="200" height="200"></OT:TNSOTPublisher>
        `

`render_style="scale" ` the options are `scale`, `fit`, `fill` defaults to `fit`
