### ISSUE TITLE
Investigate Overlaying UI Components on top of Video Stream

### ISSUE THREAD

**Issue by sean-perkins** [sean-perkins/nativescript-opentok#16]
Investigate the difficulty and possibility of overlaying native UI components on-top of the video streams, controlled from the demo app. 

Example circumstances would be:
- Play/pause buttons
- Toggle camera button (front-facing to back camera)
- Mute button 
- Dragging subscriber video stream around screen (similar to FaceTime) 

Parent issue: #12

**Comment by triniwiz** [comment]
- [x] Play/pause buttons
- [x] Toggle camera button (front-facing to back camera)
- [x] Mute button
- [x] Dragging subscriber video stream around screen (similar to FaceTime)

All of the above can be accomplished with `GridLayout`
4 . can be done with the animation
