### ISSUE TITLE
invalid parameter in subscriber.subscribe() method

### ISSUE THREAD

**Issue by darkbcx** [sean-perkins/nativescript-opentok#28]
```
    initSubscriber() {
        this.session.events.on('streamCreated', () => {
            this.subscriber.subscribe(this.session);
        });
    }
```
Got error message : ``Supplied parameters do not match any signature of call target.``

**Comment by tushar-1health** [comment]
```
    initSubscriber() {
        this.session.events.on('streamCreated', (data) => {
            this.subscriber.subscribe(this.session, data.object.get('stream'));
        });
    }
```

This will help you as subscribe needs a stream object while subscribing. 

However, this too doesn't work I tried and it shows a black screen in subscriber. 

**EDIT**:
Let me know if you come up with a solution. This is where I'm stuck right now. #29
