### ISSUE TITLE
Support in iOS and android

### ISSUE THREAD

**Issue by carldanley** [sean-perkins/nativescript-opentok#36]
Hello. My team and I are looking for a solution to integrate video chat into our Nativescript application. We're starting this portion of development in the next few days and we had a couple of questions; hoping you could help us answer them:

1. How is the support for OpenTok on mobile devices? Is this something we could use to support all sorts of arm devices? If not, is there another solution out there that can help us facilitate that?
1. Do you have any advice on using this plugin in a production environment?

**Comment by sean-perkins** [comment]
1. Please refer to OpenTok's official team/repositories. 
2. Use proper error catching to prevent app crashes + test.
