### ISSUE TITLE
integrate with Angular 2

### ISSUE THREAD

**Issue by mironcaius** [sean-perkins/nativescript-opentok#38]
Hello,
I have build an ionic 2 app. I want to add video call between users and came upon your plugin. I have looked over the wiki regarding angular 2 integration, but it does not work.

`import {TNSOTSession, TNSOTPublisher, TNSOTSubscriber} from "nativescript-opentok";`
this displays an error like: Cannot find module "nativescript-opentok"

I installed the library using this command:
`npm install nativescript-opentok --save`

Could you please help me solve this problem ?

**Comment by sean-perkins** [comment]
Angular 2 integration does work. Please refer to the demo repositories. Also make sure you are building a **Nativescript** app.
