### ISSUE TITLE
Error: Could not find module 'nativescript-opentok'

### ISSUE THREAD

**Issue by jmw-84** [sean-perkins/nativescript-opentok#6]
Hi Sean, great plugin!
When I run the demo I get the following error:
file:///app/main-view-model.js:3:37: JS ERROR Error: Could not find module 'nativescript-opentok'.

Do you know how I can fix this?
Thanks

**Comment by sean-perkins** [comment]
@jmw-84 Thank you for using the plugin. I'll look into your issue tonight!

In the mean time, I'm fairly certain you can use the plugin even with that error. The plugin successfully loads inside of the demo project and it appears to be producing the same error message.

**Comment by jmw-84** [comment]
I also get this error if it is any help:
<img width="596" alt="screen shot 2016-07-28 at 19 26 06" src="https://cloud.githubusercontent.com/assets/19305745/17222569/50a98a68-54f9-11e6-875d-56cabee0adc2.png">

Thank you

**Comment by sean-perkins** [comment]
@jmw-84 Please re-run `npm install` for this plugin and make sure you are now on `1.2.1`. I merged a pull-request to include the missing typings.

Thank you for reporting this issue. If you wouldn't mind, please close the issue or comment if the problem persists. If after a couple of days you do not reply, I'll close the issue.

PR reference: https://github.com/sean-perkins/nativescript-opentok/pull/7

**Comment by jmw-84** [comment]
Many thanks for the help. Appreciate it!
